Repository Pavel401/JobScraper-Mobile, pull requests merged in 2024-01, with the labels that each got.

#7 Added About Us page
  devtools_options.yaml
  lib/views/About/about_us.dart
  lib/views/homepage.dart
  pubspec.lock
Labels: enhancement, IWOC2024

#14 readme: modify readme and add some new features
  README.md
Labels: IWOC2024, Medium

#16 Added Code of Conduct
  CODE_OF_CONDUCT.md
Labels: IWOC2024, Medium

#22 Github greeting actions added
  .env
  .github/workflows/greetings.yml
  .gitignore
Labels: IWOC2024, Hard

#24 preview added
  lib/views/Bookmark/bookmarks_screen.dart
  lib/views/homepage.dart
  pubspec.lock
  pubspec.yaml
Labels: IWOC2024, Hard

#26 Refactor Services for Improved Performance and Maintainability
  .env
  lib/blocs/Bookmarks/bookmarks_bloc.dart
  lib/blocs/db/local_db_bloc.dart
  lib/error_handling/failure.dart
  lib/main.dart
  lib/model/job_model.dart
  lib/model/theme_model.dart
  lib/repo/job_repository.dart
  lib/services/bookmark_helper.dart
  lib/services/db_helper.dart
  lib/utility/color_util.dart
  lib/views/Bookmark/bookmarks_screen.dart
  lib/views/Search/search.dart
  lib/views/home_page.dart
  lib/widgets/circleAvatar.dart
  lib/widgets/dissmiss_widget.dart
  lib/widgets/image.dart
  lib/widgets/moving_dots.dart
  lib/widgets/toast.dart
  pubspec.lock
Labels: IWOC2024, Hard
